apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app-2
  labels:
    app: swiggy-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-app-2
  template:
    metadata:
      labels:
        app: swiggy-app-2
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: swiggy-app-2
        image: 508274233605.dkr.ecr.us-east-1.amazonaws.com/swiggy_2/swiggy_2:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
