apiVersion: v1
kind: Service
metadata:
  name: swiggy-app-1
  labels:
    app: swiggy-app-1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: swiggy-app-1
